{% set version = "3.1.3b2" %}

package:
  name: pyopengl
  version: {{ version }}

source:
  fn: PyOpenGL-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/P/PyOpenGL/PyOpenGL-{{ version }}.tar.gz
  sha256: ac73b4c0b433be02d6a55b9ed768acf07003a92a3315ba9d62bc8f8da5f0c291

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: 0

requirements:
  host:
    - pip
    - setuptools
    - python

  run:
    - python

test:
  imports:
    - OpenGL.GL

about:
  home: http://pyopengl.sourceforge.net
  license: BSD-like
  license_file: license.txt
  summary: Standard OpenGL bindings for Python
  doc_url: http://pyopengl.sourceforge.net/documentation/index.html
  doc_source_url: https://sourceforge.net/projects/pyopengl/
  dev_url: https://github.com/mcfletch/pyopengl

extra:
  recipe-maintainers:
    - almarklein
    - mcfletch
    - tadeu
