{% set version = "3.1.4" %}

package:
  name: pyopengl
  version: {{ version }}

source:
  fn: PyOpenGL-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/P/PyOpenGL/PyOpenGL-{{ version }}.tar.gz
  sha256: 0bdf5ed600df30c8830455702338902528717c0af85ac5914f1dc5aa0bfa6eee
  patches:
    - remove_redefinition_of_glGetBufferParameteriv-wrapper.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools
    - python

  run:
    - python

test:
  imports:
    - OpenGL.GL

about:
  home: http://pyopengl.sourceforge.net
  license: BSD-like
  license_file: license.txt
  summary: Standard OpenGL bindings for Python
  doc_url: http://pyopengl.sourceforge.net/documentation/index.html
  doc_source_url: https://sourceforge.net/projects/pyopengl/
  dev_url: https://github.com/mcfletch/pyopengl

extra:
  recipe-maintainers:
    - almarklein
    - mcfletch
    - tadeu
