travis:
  secure:
    BINSTAR_TOKEN: aEWoTTyKI5C29dUwgzgoGFUPHp9Kv2Q1xwaCoWntH05Fa80q3u8ZI/QqPO6/hwTttMIQcSDPRAH2vW+u6dYAGKwv9u6Pa5SEil5W11bP880ie6ooV29ub6wJ0Yb6axQ+EYthHlVUVywsO4Q2Fh0MZrfiUg16rqL7FkCl3XH9bmH1vfHQgzjoWSlP4jAOTP/xXKRkAAVsT4LYdw/fOBo5jnEcYu50N1aqZSzwocTBPiCtDui4fWKHsABQ9KEug/qChUKGdXR9naBJP9pkXHZOsXfNoe6CYLctwykOBtnuYsN6GnnSyyBA0eBzhzpOYJkZI8DhogDPJvGraYT6W7mnHLKGzzvaCPXsVuImlug1R4EDxHZzqkDrUU+w7ZR0MbKVSQ4Fh39OgnxENvOYbz3UxtPKaEEilDWXUboaPs52aRmhQ1wamJSI2xks/HD9Rod7Hyov6+LrP6NzCayFcbHptDUMA0wCm1nWTkMWjWyzdCMaUUkCRq9HOMoE1+ZxDP27J0kTmMliW+xOtynTsobTm54X+u2uH2utCYFwChWKbDHologD2IZtOWfhbrnlbM26Ap74AayED/AELwSfEDYr3BGuYSed6byUFBV/j7Ea7rX1CDd/cw4+6/NVT1IFF4Tkau/wd4B5gV0Dwv9lLGf81v3nPckYzfR9Jgq1LTe4m3g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
